[package]
name = "console_dylib"
version = "0.1.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
edition = "2021"

[dependencies]
console = { path = "../console" }
jni = "0.20"

[lib]
crate_type = ["cdylib"]
